flowershop/cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.cart, name='cart'),
]

flowershop/flowershop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
from django.urls import re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('shop.urls', 'shop'), namespace='shop')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

flowershop/shop/urls.py
from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.home, name='home'),
    path('registration/', views.registration, name='registration'),
    path('logout/', views.shop_logout, name='shop_logout'),
    path('profile/', views.profile, name='profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('main/', views.main, name='main'),
    path('about_us/', views.about_us, name='about_us'),
    path('delivery/', views.delivery, name='delivery'),
    path('payment/', views.payment, name='payment'),
    path('pro_tovar/<int:id>/', views.pro_tovar, name='pro_tovar'),
    path('sposob_oplaty/<int:order_id>', views.sposob_oplaty, name='sposob_oplaty'),
    path('oplata/<int:order_id>', views.oplata, name='oplata'),
]

flowershop/shop/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

# Create your models here.
class FlowerType(models.Model):
    name = models.CharField(max_length=50, unique=True)
 
    def __str__(self):
        return self.name
    
class Bouquet(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва букета")
    flowers = models.ManyToManyField(FlowerType, related_name="bouquets", verbose_name="Квіти у складі")
    composition = models.TextField(verbose_name="Склад")
    description = models.TextField(verbose_name="Опис")
    price = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Ціна")
    new_price = models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True, verbose_name="Нова ціна")
    image = models.ImageField(upload_to="bouquets/", verbose_name="Зображення")

    def __str__(self):
            return self.name
    
    def get_absolute_url(self):
        return reverse('shop:pro_tovar', args=[str(self.id)])
    
    def discount(self):
        if self.new_price:
            return round((self.price - self.new_price) / self.price * 100)
        return None
        
class BouquetReview(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bouquet = models.ForeignKey(Bouquet, on_delete=models.CASCADE, related_name='reviews')
    text = models.TextField(verbose_name='Відгук')
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = "Відгук"
        verbose_name_plural = "Відгуки"
        
    def __str__(self):
        return f"Відгук від {self.user.email} на {self.bouquet.name}"
    

class UserData(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    telephone = models.CharField(max_length=20)
    
    class Meta:
        verbose_name = 'UserData'
        verbose_name_plural = 'UserData'
        
    def __str__(self) -> str:
        return self.user.email

flowershop/shop/forms.py
from django import forms
from .models import *
from django.contrib.auth import get_user_model, password_validation

CustomUser = get_user_model()

class LoginForm(forms.Form):
    username = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'name': 'username',
        }),
        required=True
    )
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'name':'password'
        })
    )
    
class RegistrationForm(forms.ModelForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'name':'password'
        })
    )
    
    class Meta:
        model = CustomUser
        fields = ['first_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'name': 'first_name'}),
            'email': forms.EmailInput(attrs={'name': 'email'}),
        }
        
class EditProfileForm(forms.ModelForm):
    email = forms.EmailField(
    widget=forms.EmailInput(attrs={
        'id': 'email', 
        'name': 'email',
    }), 
    required=True
    ) 
    
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'name': 'first_name',
        }),
        max_length=100, 
        required=True
    )
    
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={
            'name': 'last_name',
        }),
        max_length=100, 
        required=True
    )
    
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email']
    

class EditPhoneForm(forms.ModelForm):
    class Meta:
        model = UserData
        fields = ['telephone'] 
        widgets = {
            'telephone': forms.TextInput(attrs= {
                'name': 'phone',
                'type': 'tel',
            })
        }
        
        
class UserDeleteForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = []
        
class ChangePasswordForm(forms.Form):
    
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'name': 'old_password'
        }),
        required=True
    )
    
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'name': 'new_password1'
        }),
        required=True,
        validators=[password_validation.validate_password]
    )
    
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'name': 'new_password2'
        }),
        required=True
    )
    
    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('new_password1')
        p2 = cleaned_data.get('new_password2')
        if p1 and p2 and p1 != p2:
            self.add_error('new_password2', 'Паролі не співпадають.')
        return cleaned_data
    
class BouquetReviewForm(forms.ModelForm):
    class Meta:
        model = BouquetReview
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={
                'placeholder': 'Чудові квіти!',
            })
        }

flowershop/shop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from .forms import *
from .models import *
from cart.cart import Cart
from orders.models import *
from django.core.paginator import Paginator
from django.db.models import Q, F, Value, DecimalField
from django.db.models.functions import Coalesce
from django.db.models.functions import Lower


# изменения не нужны
def about_us(request):
    return render(request, 'shop/ProNas_info.html')
def delivery(request):
    return render(request, 'shop/dostavka_info.html')
def payment(request):
    return render(request, 'shop/oplata_info.html')

# login
def home(request):
    form = LoginForm(request.POST or None)
     
    if request.method == "POST" and form.is_valid():
        email = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        user = authenticate(request, username=email, password=password)
        
        if user is not None:
            login(request, user)
            return redirect('shop:profile')
        else:
            form.add_error(None, 'Невірна пошта або пароль.')
    
    latest_reviews = BouquetReview.objects.select_related('bouquet').order_by('-created_at')[:3]
    
    return render(request, 'shop/home.html', {
        'form': form, 
        'latest_reviews': latest_reviews,
    })


def registration(request):
    form = RegistrationForm(request.POST or None)
    if request.method == "POST" and form.is_valid():
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()
        login(request, user)
        return redirect('shop:profile')
    
    latest_reviews = BouquetReview.objects.select_related('bouquet').order_by('-created_at')[:3]
    
    return render(request, 'shop/registration.html', {
        'form': form,
        'latest_reviews': latest_reviews,
    })

# logout
def shop_logout(request):
    logout(request)
    return redirect('shop:home')


@login_required(login_url='shop:home')
def profile(request):
    user = request.user
    user_data, created = UserData.objects.get_or_create(user=user)
    
    if request.method == 'POST':
        if 'update' in request.POST:
            edit_account_form = EditProfileForm(request.POST, instance=user)
            edit_phone_form = EditPhoneForm(request.POST, instance=user_data)
            
            if edit_account_form.is_valid() and edit_phone_form.is_valid():
                edit_account_form.save()
                phone = edit_phone_form.cleaned_data.get('telephone')
                user_data.telephone = phone
                user_data.save()
        elif 'delete-acc' in request.POST:
            delete_user_form = UserDeleteForm(request.POST, instance=user)
            if delete_user_form.is_valid():
                if not user.is_superuser and not user.is_staff:
                    user.delete()
                    
        return redirect(f'{request.path}')
    
    edit_account_form = EditProfileForm(instance=user)
    edit_phone_form = EditPhoneForm(instance=user_data)
    delete_user_form = UserDeleteForm(instance=request.user)
    
    return render(request, 'shop/profile.html', {
        'edit_account_form': edit_account_form,
        'edit_phone_form': edit_phone_form,
    })
    
    
@login_required(login_url='shop:home')
def change_password(request):
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            user = request.user
            if not user.check_password(form.cleaned_data['old_password']):
                form.add_error('old_password', 'Неправильний старий пароль.')
            else:
                user.set_password(form.cleaned_data['new_password1'])
                user.save()
                update_session_auth_hash(request, user)  # prevents logout
                return redirect('shop:profile')
    else:
        form = ChangePasswordForm()
        
    return render(request, 'shop/change_password.html', {'form': form})



def main(request):
    query = request.GET.get('q', '')
    flower_type = request.GET.get('flower_type', '')
    price_order = request.GET.get('price_order', '')
    bouquets = Bouquet.objects.all()
    
    if query:
        bouquets = bouquets.annotate(
            lower_name=Lower('name'),
            lower_composition=Lower('composition')
        ).filter(
            Q(lower_name__contains=query.lower()) |
            Q(lower_composition__contains=query.lower())
        )
    if flower_type:
        bouquets = bouquets.filter(flowers__name=flower_type)
    
    if price_order == 'asc':
        bouquets = bouquets.annotate(
            effective_price=Coalesce('new_price', 'price', output_field=DecimalField())
        ).order_by('effective_price')

    elif price_order == 'desc':
        bouquets = bouquets.annotate(
            effective_price=Coalesce('new_price', 'price', output_field=DecimalField())
        ).order_by('-effective_price')
    
    paginator = Paginator(bouquets, 8)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    flower_types = FlowerType.objects.all()
    
    context = {
        'flower_types': flower_types,
        'bouquets': page_obj
    }
    return render(request, 'shop/main.html', context)



def pro_tovar(request, id):
    bouquet = get_object_or_404(Bouquet, id=id)
    reviews = bouquet.reviews.all()
    
    if request.method == 'POST':
        if 'send-review' in request.POST:
            if not request.user.is_authenticated:
                return redirect('shop:home')
            review_form = BouquetReviewForm(request.POST)
            if review_form.is_valid():
                review = review_form.save(commit=False)
                review.bouquet = bouquet
                review.user = request.user
                review.save()
                return redirect('shop:pro_tovar', id=bouquet.id)
        
        if 'add-to-cart' in request.POST:
            cart = Cart(request)
            quantity = int(request.POST.get('quantity', 1))
            cart.add(bouquet, quantity)
            return redirect('shop:pro_tovar', id=bouquet.id)
        
    else:
        review_form = BouquetReviewForm()
        
    
    paginator = Paginator(reviews, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'bouquet': bouquet,
        'review_form': review_form,
        'reviews': page_obj.object_list,
        'page_obj': page_obj,
    }
    
    return render(request, 'shop/pro_tovar.html', context)



def sposob_oplaty(request, order_id):

    last_order = get_object_or_404(Order, id=order_id, user=request.user, is_active=True)
    if last_order.status != 'cart':
        return redirect('cart:cart')

    if request.method == "POST":
        
        if 'continue' in request.POST:
            payment_method = request.POST.get("payment_method")
            if payment_method:
                last_order.payment_method = payment_method
                last_order.status = 'payment_method'
                last_order.save()
                
                if payment_method == "cash":
                    return redirect('orders:order', order_id=last_order.id)
                else:
                    return redirect('shop:oplata', order_id=last_order.id)

    return render(request, 'shop/sposob_oplaty.html', {
        'last_order': last_order,
    })


def oplata(request, order_id):
    
    order = get_object_or_404(Order, id=order_id, user=request.user, is_active=True)
    if order.status != 'payment_method':
        return redirect('shop:sposob_oplaty', order.id)
    
    if request.method == "POST":
        if 'pay' in request.POST:
            order.is_paid = True
            order.status = 'paid'
            order.is_active = False
            order.save()
            return redirect('orders:order', order_id=order.id)
    
    return render(request, 'shop/oplata.html', {
        'order': order,
    })

flowershop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link href='https://fonts.googleapis.com/css?family=Montserrat Alternates' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "shop/css/base.css" %}">
    {% block css_links %}
    {% endblock css_links %}
    <title>Document</title>
</head>
<body> 
    <header class="header">

        <div class="nav-container">

            <div class="logo">
                <a href="{% url "shop:main" %}">єКв
                    {% block logo_img %}
                    <img src="{% static "shop/images/Vector.png" %}" alt="і" class="icon">ти
                    {% endblock logo_img %}
                </a>
            </div>
    
            <div class="nav-items">
                <div class="info">
    
                    <li class="info about-us">
                        <a href="{% url "shop:about_us" %}" class="nav-link">Про нас</a>
                    </li>
                    
                    <li class="info delivery">
                        <a href="{% url "shop:delivery" %}" class="nav-link">Доставка</a>
                    </li>
                    
                    <li class="info payment">
                        <a href="{% url "shop:payment" %}" class="nav-link">Оплата</a>
                    </li>
                    
                    <li class="info number">
                        <a href="" class="nav-link">+38 (095) 432 1232</a>
                    </li>
    
                </div>
                <div class="icons">
     
                    <li class="icons cart">
                        <a href="{% url "cart:cart" %}" class="nav-link">
                            {% if cart|length > 0 %}
                                <i class="bi bi-bag-check"></i>
                            {% else %}
                                <i class="bi bi-bag"></i>
                            {% endif %} 
                        </a>
                    </li>
    
                    <li class="icons account">
                        <a href="{% url "shop:profile" %}" class="nav-link"> <i class="bi bi-person-circle"></i></a>
                    </li>
                    
                </div>
            </div>

        </div>
    </header>

    {% block content %}
    {% endblock content %} 

    <button id="back-to-top" class="back-to-top"><i class="bi bi-chevron-up"></i></button>
    
    <footer class="footer">
        
        <div class="footer-sec main-page">
            <li class="footer-list"><a href="{% url "shop:main" %}">На головну</a></li>
        </div>

        <div class="footer-sec socials">
            <p class="footer-list">Наші соц. мережі</p>
            <li class="footer-list"><a href="https://www.instagram.com/ekvity_ua?igsh=MWE0ZTFodTE5NWIzag==">Instagram</a></li>
            <li class="footer-list"><a href="#">Facebook</a></li>
            <li class="footer-list"><a href="#">LinkedIn</a></li>
            <li class="footer-list"><a href="#">X</a></li>
        </div>

        <div class="footer-sec contacts">
            <p class="footer-list">Контакти</p>
            <li class="footer-list"><a href="#">+38 (095) 432 1232</a></li>
        </div>
        
        <section class="poloska"></section>

    </footer>

    <script src="{% static "shop/js/back-to-top-btn.js" %}"></script>

    {% block scripts %}
    {% endblock scripts %} 

</body>
</html>

flowershop/templates/shop/home.html
<!doctype html>
<html lang="uk">
    
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>єКвіти</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "shop/css/home.css" %}">
</head> 

<body>
    <div class="container">
        <div class="left">
            <p class="logo">
                єКв
                <img src="{% static "shop/images/download.png" %}" alt="і" class="icon">
                ти
            </p>


            <h1>Сервіс для швидкого пошуку якісних квітів</h1>
            <h3>Наші соц. мережі</h3>
            <div class="socials">
                <a href="https://www.instagram.com/ekvity_ua?igsh=MWE0ZTFodTE5NWIzag=="><img src="{% static "shop/images/insta.png" %}" alt="Instagram"></a>
                <a href="#"><img src="{% static "shop/images/linkedin.png" %}" alt="LinkedIn"></a>
                <a href="#"><img src="{% static "shop/images/facebook.png" %}" alt="Facebook"></a>
                <a href="#"><img src="{% static "shop/images/twitter.png" %}" alt="X"></a>
            </div>
        </div>

        <div class="right">
            <h2>Ласкаво просимо!</h2>
            <form method="post" action="{% url 'shop:home' %}" class="login-form">
                {% csrf_token %}

                <div class="form-group">
                    <label for="username">Пошта</label>
                    {{ form.username }}
                </div>

                <div class="form-group">
                    <label for="password">Пароль</label>
                    {{ form.password }}
                </div>

                {% if form.errors %}
                    <p class="error-message">Невірна пошта або пароль.</p>
                {% endif %}

                <button type="submit" class="login-btn">Увійти</button>
            </form>

            <a href="{% url "shop:registration" %}">
                <button class="register-btn">Немає акаунту? Зареєструйтеся!</button>
            </a>
        </div>
    </div>

    <div class="below">
        <h2>Чому нам довіряють?</h2>
        <div class="text-image">
            <img src="{% static "shop/images/Frame.png" %}" alt="і" class="image">
            <p>
                Ми дбаємо про кожну деталь: від<br>
                свіжості квітів до вчасної доставки.<br>
                Наші клієнти отримують саме ті<br>
                букети, які замовляють, без<br>
                неприємних сюрпризів. Прозорі ціни,<br>
                зручна оплата та щирий сервіс<br>
                роблять нас надійним вибором для<br>
                найважливіших моментів.
            </p>
        </div>
        <div class="client">
            <h3>Ставай нашим<br> постійним клієнтом і<br> отримуй знижку -10%</h3>
        </div>
        <div class="reviews">
            <h3>відгуки</h4>
                <p>Прочитай, Що Є Сказати Іншим</p>
        </div>
        <div class="cards">
            {% for review in latest_reviews %}
                <div class="card">
                    <h4>{{ review.user.first_name }} {% if review.user.last_name %}{{review.user.last_name}}{% endif %}</h4>
                    <p>{{ review.text | truncatewords:25 }}</p>
                    <a href="{{ review.bouquet.get_absolute_url }}" class="review-link">Перейти до букета</a>
                </div>
            {% endfor %}

        </div>
        <div class="gradient-box-wrapper">
            <div class="fog fog1"></div>
            <div class="fog fog2"></div>
            <div class="gradient-box">
                <p class="gradient-p">ARE YOU READY?</p>
                <span class="gradient-text">Стань Причиною Гарного <br> Настрою Близьких Людей</span>
                <a href="{% url "shop:main" %}">
                    <button class="gradient-btn">РОЗПОЧАТИ</button>
                </a>

            </div>
        </div>

        <footer class="footer">

            <div class="footer-sec main-page">
                <li class="footer-list"><a href="{% url "shop:main" %}">Головна</a></li>
            </div>

            <div class="footer-sec socials">
                <p class="footer-list">Наші соц. мережі</p>
                <li class="footer-list"><a href="https://www.instagram.com/ekvity_ua?igsh=MWE0ZTFodTE5NWIzag==">Instagram</a></li>
                <li class="footer-list"><a href="#">Facebook</a></li>
                <li class="footer-list"><a href="#">LinkedIn</a></li>
                <li class="footer-list"><a href="#">X</a></li>
            </div>

            <div class="footer-sec contacts">
                <p class="footer-list">Контакти</p>
                <li class="footer-list"><a>+38 (095) 432 1232</a></li>
            </div>

        </footer>


    </div>
    <div class="footer-line"></div>


</body>

</html>

flowershop/templates/shop/profile.html
{% extends "shop/base.html" %}
{% block css_links %}
{% load static %}
<link rel="stylesheet" href="{% static "shop/css/profile.css" %}">
{% endblock css_links %}

{% block content %}
    <div class="inform">
        <h1 class="info-name">Інформація про акаунт</h1>
        <form class="profile-form" method="POST" action="{% url "shop:profile" %}">
            {% csrf_token %}
            <div class="form-grid">
            
                <div class="form-group">
                    <label for="first_name">Ім'я</label>
                    {{edit_account_form.first_name}}
                </div>

                <div class="form-group">
                    <label for="phone">Номер телефону</label>
                    {{edit_phone_form.telephone}}
                </div>

                <div class="form-group">
                    <label for="last_name">Прізвище</label>
                    {{edit_account_form.last_name}}
                </div>

                <div class="form-group">
                    <label for="email">e-mail</label>
                    {{edit_account_form.email}}
                </div>

                <div class="form-actions">
                    <button type="submit" class="update-btn" name='update'>Оновити дані</button>
                </div>

                
                <div class="form-group logout-action">
                    <a href="{% url "shop:shop_logout" %}" class="logout-link">Вийти з акаунту <i class="bi bi-box-arrow-right"></i></a>
                </div>
                
            </div>
        </form>

        <div class="bottom-part">
            <div class="password-info">
                <div class="form-group">
                    <div class="password-label-group">
                        <a href="{% url "shop:change_password" %}">Змінити пароль</a>
                    </div>
                </div>
            </div>
    
            <div class="delete-account">
                <form class="form-group delete-action" method='POST'>
                    {% csrf_token %}
                    {{delete_user_form.as_p}}
                    <button type='submit' class="delete-link" name='delete-acc'>Видалити акаунт</button>
                </form>
            </div>
        </div>

    </div>
{% endblock content %}

{% block scripts %}
{% endblock scripts %}

flowershop/templates/shop/registration.html
<!doctype html>
<html lang="uk">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>єКвіти</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "shop/css/registration.css" %}">
</head> 

<body>
    <div class="container">
        <div class="left">
            <p class="logo">
                єКв
                <img src="{% static "shop/images/pinkVector.png" %}" alt="і" class="icon">
                ти
            </p>


            <h1>Сервіс для швидкого пошуку якісних квітів</h1>
            <h3>Наші соц. мережі</h3>
            <div class="socials">
                <a href="https://www.instagram.com/ekvity_ua?igsh=MWE0ZTFodTE5NWIzag=="><img src="{% static "shop/images/pink1.png" %}" alt="Instagram"></a>
                <a href="#"><img src="{% static "shop/images/pink2.png" %}" alt="LinkedIn"></a>
                <a href="#"><img src="{% static "shop/images/pink3.png" %}" alt="Facebook"></a>
                <a href="#"><img src="{% static "shop/images/pink4.png" %}" alt="X"></a>
            </div>
        </div>

        <div class="right">
            <h2>Ласкаво просимо!</h2>
            <form action="{% url "shop:registration" %}" method='POST'>
                {% csrf_token %}
                <div class="form-group">
                    <label for="first_name">Ім'я</label>
                    {{form.first_name}}
                </div>
                <div class="form-group">
                    <label for="email">Пошта</label>
                    {{form.email}}
                </div>
                <div class="form-group">
                    <label for="password">Пароль</label>
                    {{form.password}}
                </div>

                {% if form.errors %}
                    <p class="error-message">Невірна пошта або пароль.</p>
                {% endif %}

                <button class="login-btn" type='submit'>Зареєструватися</button>
            </form>
            <a href="{% url "shop:home" %}"><button class="register-btn">Є акаунт? Увійти</button></a>
        </div> 

    </div>
    </div>

    <div class="below">
        <h2>Чому нам довіряють?</h2>
        <div class="text-image">
            <img src="{% static "shop/images/Frame2.png" %}" alt="і" class="image">
            <p>
                Ми дбаємо про кожну деталь: від<br>
                свіжості квітів до вчасної доставки.<br>
                Наші клієнти отримують саме ті<br>
                букети, які замовляють, без<br>
                неприємних сюрпризів. Прозорі ціни,<br>
                зручна оплата та щирий сервіс<br>
                роблять нас надійним вибором для<br>
                найважливіших моментів.
            </p>
        </div> 
        <div class="client">
            <h3>Ставай нашим<br> постійним клієнтом і<br> отримуй знижку -10%</h3>
        </div>
        <div class="reviews">
            <h3>відгуки</h4>
                <p>Прочитай, Що Є Сказати Іншим</p>
        </div>
        <div class="cards">
            {% for review in latest_reviews %}
                <div class="card">
                    <h4>{{ review.user.first_name }} {% if review.user.last_name %}{{review.user.last_name}}{% endif %}</h4>
                    <p>{{ review.text | truncatewords:25 }}</p>
                    <a href="{{ review.bouquet.get_absolute_url }}" class="review-link">Перейти до букета</a>
                </div>
            {% endfor %}
        </div>
        <div class="gradient-box-wrapper">
            <div class="fog fog1"></div>
            <div class="fog fog2"></div>
            <div class="gradient-box">
                <p class="gradient-p">ARE YOU READY?</p>
                <span class="gradient-text">Стань Причиною Гарного <br> Настрою Близьких Людей</span>
                <a href="{% url "shop:main" %}">
                    <button class="gradient-btn">РОЗПОЧАТИ</button>
                </a>

            </div>
        </div>

        <footer class="footer">

            <div class="footer-sec main-page">
                <li class="footer-list"><a href="{% url "shop:main" %}">Головна</a></li>
            </div>

            <div class="footer-sec socials">
                <p class="footer-list">Наші соц. мережі</p>
                <li class="footer-list"><a href="https://www.instagram.com/ekvity_ua?igsh=MWE0ZTFodTE5NWIzag==">Instagram</a></li>
                <li class="footer-list"><a href="#">Facebook</a></li>
                <li class="footer-list"><a href="#">LinkedIn</a></li>
                <li class="footer-list"><a href="#">X</a></li>
            </div>

            <div class="footer-sec contacts">
                <p class="footer-list">Контакти</p>
                <li class="footer-list"><a>+38 (095) 432 1232</a></li>
            </div>

        </footer>


    </div>
    <div class="footer-line"></div>


</body>

</html>